"""Database logic for fin_assist (Oracle schema + helpers)."""

import json
import os
from datetime import datetime
from typing import Optional

import oracledb

from config.settings import (
    DEFAULT_USER_INITIAL_CAPITAL,
    DEFAULT_USER_MAX_ALLOCATION,
    DEFAULT_USER_RISK_PER_TRADE,
    DEFAULT_USER_WALLET,
    NEWS_CACHE_FILE,
    PROFIT_TARGET_PCT,
    STOP_LOSS_PCT,
    SYSTEM_USERNAME,
)
from infra.logging import log

MAX_SNAPS = 200


def _get_conn():
    return oracledb.connect(
        user=os.getenv("ORACLE_DB_USER"),
        password=os.getenv("ORACLE_DB_PASSWORD"),
        dsn=os.getenv("ORACLE_DB_DSN"),
    )


def _rows(cursor):
    cols = [c[0].lower() for c in cursor.description]
    return [dict(zip(cols, r)) for r in cursor.fetchall()]


def _create_table(c, ddl: str):
    c.execute(f"BEGIN EXECUTE IMMEDIATE q'[{ddl}]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;")


def _create_or_replace(c, ddl: str):
    c.execute(f"BEGIN EXECUTE IMMEDIATE q'[{ddl}]'; END;")


def initialize_db():
    conn = _get_conn()
    c = conn.cursor()
    _create_table(c, """CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(255) NOT NULL UNIQUE,
        password VARCHAR2(255),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        wallet_balance NUMBER(18,6) NOT NULL CHECK(wallet_balance >= 0),
        initial_capital NUMBER(18,6) NOT NULL CHECK(initial_capital > 0),
        risk_per_trade NUMBER(8,6) NOT NULL CHECK(risk_per_trade > 0 AND risk_per_trade <= 1),
        max_allocation_pct NUMBER(8,6) NOT NULL CHECK(max_allocation_pct > 0 AND max_allocation_pct <= 1),
        rl_enabled NUMBER(1) NOT NULL DEFAULT 1 CHECK(rl_enabled IN (0,1)),
        notes CLOB
    )""")
    _create_table(c, """CREATE TABLE positions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        symbol VARCHAR2(32) NOT NULL,
        quantity NUMBER NOT NULL CHECK(quantity > 0),
        entry_price NUMBER(18,6) NOT NULL CHECK(entry_price > 0),
        entry_time TIMESTAMP NOT NULL,
        stop_loss NUMBER(18,6) NOT NULL CHECK(stop_loss > 0),
        target_price NUMBER(18,6) NOT NULL CHECK(target_price > 0),
        rl_confidence NUMBER(8,6),
        guardrail_reason CLOB,
        status VARCHAR2(16) NOT NULL DEFAULT 'OPEN' CHECK(status='OPEN'),
        CONSTRAINT uq_positions_user_symbol UNIQUE(user_id, symbol)
    )""")
    _create_table(c, """CREATE TABLE trades (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        symbol VARCHAR2(32) NOT NULL,
        position_id NUMBER REFERENCES positions(id),
        side VARCHAR2(32) NOT NULL,
        quantity NUMBER, price NUMBER(18,6), pnl NUMBER(18,6), pnl_pct NUMBER(18,6),
        rl_score NUMBER(10,6), reward NUMBER(18,6), metadata CLOB, guardrail_reason CLOB,
        research_alignment NUMBER(1), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""")
    _create_table(c, """CREATE TABLE snapshots (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        symbol VARCHAR2(32) NOT NULL, timestamp TIMESTAMP NOT NULL, price NUMBER(18,6) NOT NULL,
        vwap NUMBER(18,6), rsi NUMBER(10,6), atr NUMBER(18,6), volume NUMBER(18,6),
        pct_from_low NUMBER(10,6), pct_from_high NUMBER(10,6), position_flag NUMBER(1) NOT NULL CHECK(position_flag IN (0,1)),
        unrealized_pnl NUMBER(18,6), wallet_utilization NUMBER(10,6), state_vector CLOB NOT NULL
    )""")
    _create_table(c, """CREATE TABLE news_cache (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol VARCHAR2(32) NOT NULL, headline VARCHAR2(1000) NOT NULL,
        sentiment_score NUMBER(10,6), source VARCHAR2(255), published_at TIMESTAMP,
        fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_news UNIQUE(symbol, headline)
    )""")
    _create_table(c, """CREATE TABLE research_runs (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        symbol VARCHAR2(32) NOT NULL, ema_signal NUMBER, rsi_signal NUMBER, vwap_signal NUMBER, volume_signal NUMBER,
        composite_signal NUMBER(18,6), rl_action VARCHAR2(32), rl_score NUMBER(10,6), guardrail_reason CLOB,
        news_hits NUMBER, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""")
    for ddl in [
        "CREATE INDEX idx_positions_user_symbol ON positions(user_id, symbol)",
        "CREATE INDEX idx_trades_user_symbol ON trades(user_id, symbol)",
        "CREATE INDEX idx_snapshots_symbol_time ON snapshots(symbol, timestamp)",
    ]:
        try:
            c.execute(ddl)
        except oracledb.DatabaseError:
            pass
    _create_or_replace(c, """CREATE OR REPLACE TRIGGER trg_validate_sell_position
        BEFORE INSERT ON trades
        FOR EACH ROW
        BEGIN
            IF :NEW.side = 'SELL' AND :NEW.position_id IS NULL THEN
                RAISE_APPLICATION_ERROR(-20001, 'SELL requires position_id');
            END IF;
        END;""")
    _create_or_replace(c, """CREATE OR REPLACE PROCEDURE pr_upsert_user (
        p_username IN VARCHAR2,
        p_password IN VARCHAR2,
        p_wallet IN NUMBER,
        p_initial_capital IN NUMBER,
        p_risk_per_trade IN NUMBER,
        p_max_allocation_pct IN NUMBER,
        p_notes IN CLOB
    ) AS
    BEGIN
        MERGE INTO users u USING (SELECT p_username username FROM dual) s ON (u.username=s.username)
        WHEN MATCHED THEN UPDATE SET
          password=COALESCE(p_password, u.password), wallet_balance=p_wallet, initial_capital=p_initial_capital,
          risk_per_trade=p_risk_per_trade, max_allocation_pct=p_max_allocation_pct, notes=p_notes
        WHEN NOT MATCHED THEN INSERT (username,password,wallet_balance,initial_capital,risk_per_trade,max_allocation_pct,notes)
          VALUES (p_username,p_password,p_wallet,p_initial_capital,p_risk_per_trade,p_max_allocation_pct,p_notes);
    END;""")
    _create_or_replace(c, """CREATE OR REPLACE PROCEDURE pr_set_user_wallet (
        p_username IN VARCHAR2,
        p_wallet IN NUMBER
    ) AS
    BEGIN
        UPDATE users SET wallet_balance = p_wallet WHERE username = p_username;
    END;""")
    _create_or_replace(c, """CREATE OR REPLACE FUNCTION fn_adjust_user_wallet (
        p_username IN VARCHAR2,
        p_delta IN NUMBER
    ) RETURN NUMBER AS
        v_wallet NUMBER;
    BEGIN
        UPDATE users
        SET wallet_balance = wallet_balance + p_delta
        WHERE username = p_username
        RETURNING wallet_balance INTO v_wallet;
        RETURN v_wallet;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END;""")
    _create_or_replace(c, """CREATE OR REPLACE PROCEDURE pr_upsert_position (
        p_user_id IN NUMBER,
        p_symbol IN VARCHAR2,
        p_quantity IN NUMBER,
        p_entry_price IN NUMBER,
        p_entry_time IN TIMESTAMP,
        p_stop_loss IN NUMBER,
        p_target_price IN NUMBER,
        p_guardrail_reason IN CLOB,
        p_rl_confidence IN NUMBER
    ) AS
    BEGIN
        MERGE INTO positions p USING (SELECT p_user_id user_id, p_symbol symbol FROM dual) s ON (p.user_id=s.user_id AND p.symbol=s.symbol)
        WHEN MATCHED THEN UPDATE SET quantity=p_quantity, entry_price=p_entry_price, entry_time=p_entry_time, stop_loss=p_stop_loss, target_price=p_target_price, guardrail_reason=p_guardrail_reason, rl_confidence=p_rl_confidence
        WHEN NOT MATCHED THEN INSERT (user_id,symbol,quantity,entry_price,entry_time,stop_loss,target_price,guardrail_reason,rl_confidence,status)
          VALUES (p_user_id,p_symbol,p_quantity,p_entry_price,p_entry_time,p_stop_loss,p_target_price,p_guardrail_reason,p_rl_confidence,'OPEN');
    END;""")
    conn.commit()
    conn.close()
    ensure_user_profile(SYSTEM_USERNAME)
    _seed_news_cache_from_file()


def fetch_user(username: str):
    conn = _get_conn(); c = conn.cursor()
    c.execute("SELECT * FROM users WHERE username = :1", [username])
    rows = _rows(c); conn.close()
    return rows[0] if rows else None


def get_user_id(username: str):
    row = fetch_user(username)
    return row["id"] if row else None


def ensure_user_profile(username, wallet=None, initial_capital=None, risk_per_trade=None, max_allocation_pct=None, password=None, notes=""):
    row = fetch_user(username)
    if row:
        return row
    upsert_user(
        username,
        wallet if wallet is not None else DEFAULT_USER_WALLET,
        initial_capital if initial_capital is not None else DEFAULT_USER_INITIAL_CAPITAL,
        risk_per_trade if risk_per_trade is not None else DEFAULT_USER_RISK_PER_TRADE,
        max_allocation_pct if max_allocation_pct is not None else DEFAULT_USER_MAX_ALLOCATION,
        password=password,
        notes=notes,
    )
    return fetch_user(username)


def upsert_user(username, wallet, initial_capital, risk_per_trade, max_allocation_pct, password=None, notes=""):
    conn = _get_conn(); c = conn.cursor()
    c.callproc("pr_upsert_user", [username, password, wallet, initial_capital, risk_per_trade, max_allocation_pct, notes])
    conn.commit(); conn.close()


def adjust_user_wallet(username, delta):
    conn = _get_conn(); c = conn.cursor()
    result = c.callfunc("fn_adjust_user_wallet", oracledb.DB_TYPE_NUMBER, [username, delta])
    conn.commit(); conn.close()
    return float(result) if result is not None else None


def update_user_wallet(username, wallet):
    conn = _get_conn(); c = conn.cursor()
    c.callproc("pr_set_user_wallet", [username, wallet])
    conn.commit(); conn.close()


def get_wallet_balance(username):
    row = fetch_user(username)
    return float(row["wallet_balance"] or 0.0) if row else 0.0


def record_trade_decision(symbol, action, price, metadata, username, position_id=None, **extras):
    conn = _get_conn(); c = conn.cursor()
    c.execute("SELECT id FROM users WHERE username = :1", [username]); r = c.fetchone()
    if not r:
        conn.close(); raise ValueError(f"Unknown user {username}")
    c.execute("""INSERT INTO trades (user_id,symbol,position_id,side,quantity,price,pnl,pnl_pct,rl_score,reward,metadata,guardrail_reason,research_alignment)
                 VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13)""",
              [r[0], symbol.upper(), position_id, action, extras.get("quantity"), price, extras.get("pnl"), extras.get("pnl_pct"),
               extras.get("rl_score"), extras.get("reward"), str(metadata), extras.get("guardrail"), extras.get("aligned", 0)])
    conn.commit(); conn.close()


def get_open_positions(user_id=None):
    conn = _get_conn(); c = conn.cursor()
    if user_id is None:
        c.execute("SELECT id, user_id, symbol, quantity as qty, entry_price as price FROM positions WHERE status='OPEN'")
    else:
        c.execute("SELECT id, user_id, symbol, quantity as qty, entry_price as price FROM positions WHERE status='OPEN' AND user_id=:1", [user_id])
    rows = _rows(c); conn.close()
    return rows


def upsert_position(user_id, symbol, quantity, entry_price, stop_loss, target_price, guardrail_reason=None, rl_confidence=None):
    conn = _get_conn(); c = conn.cursor()
    c.callproc("pr_upsert_position", [user_id, symbol.upper(), quantity, entry_price, datetime.utcnow(), stop_loss, target_price, guardrail_reason, rl_confidence])
    conn.commit(); conn.close()


def delete_position(user_id, symbol):
    conn = _get_conn(); c = conn.cursor()
    c.execute("DELETE FROM positions WHERE user_id=:1 AND symbol=:2", [user_id, symbol.upper()])
    conn.commit(); conn.close()


def insert_snapshot(symbol, stats, timestamp):
    conn = _get_conn(); c = conn.cursor()
    c.execute("""INSERT INTO snapshots (user_id,symbol,timestamp,price,vwap,rsi,atr,volume,pct_from_low,pct_from_high,position_flag,unrealized_pnl,wallet_utilization,state_vector)
                 VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13,:14)""",
              [stats.get("user_id", 1), symbol.upper(), timestamp, stats.get("price"), stats.get("vwap"), stats.get("rsi"), stats.get("atr"),
               stats.get("avg_volume"), stats.get("pct_from_low"), stats.get("pct_from_high"), stats.get("position_flag", 0),
               stats.get("unrealized_pnl"), stats.get("wallet_util"), stats.get("state_vector", "{}")])
    if MAX_SNAPS:
        c.execute("DELETE FROM snapshots WHERE id NOT IN (SELECT id FROM (SELECT id FROM snapshots ORDER BY timestamp DESC) WHERE ROWNUM <= :1)", [MAX_SNAPS])
    conn.commit(); conn.close()


def fetch_news_cache(symbol):
    conn = _get_conn(); c = conn.cursor()
    c.execute("SELECT headline, sentiment_score, source, fetched_at FROM news_cache WHERE symbol = :1", [symbol.upper()])
    rows = _rows(c); conn.close(); return rows


def upsert_news_cache(symbol, headlines):
    conn = _get_conn(); c = conn.cursor()
    for entry in headlines:
        c.execute("""MERGE INTO news_cache n USING (SELECT :1 symbol, :2 headline FROM dual) s ON (n.symbol=s.symbol AND n.headline=s.headline)
                     WHEN NOT MATCHED THEN INSERT (symbol, headline, sentiment_score, source, published_at, fetched_at)
                     VALUES (:1,:2,:3,:4,:5,:6)""",
                  [symbol.upper(), entry.get("title"), entry.get("score"), entry.get("source"), entry.get("published_at"), datetime.utcnow()])
    conn.commit(); conn.close()


def record_research_run(user_id, symbol, payload):
    conn = _get_conn(); c = conn.cursor()
    c.execute("""INSERT INTO research_runs (user_id,symbol,ema_signal,rsi_signal,vwap_signal,volume_signal,composite_signal,rl_action,rl_score,guardrail_reason,news_hits)
                 VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11)""",
              [user_id, symbol.upper(), payload.get("ema_signal"), payload.get("rsi_signal"), payload.get("vwap_signal"), payload.get("volume_signal"),
               payload.get("composite_signal"), payload.get("rl_action"), payload.get("rl_score"), payload.get("guardrail_reason"), payload.get("news_hits")])
    conn.commit(); conn.close()


def _default_stop_target(price: float):
    price = price if price > 0 else 1.0
    stop_loss = max(price * (1 - STOP_LOSS_PCT), 0.01)
    target_price = max(price * (1 + PROFIT_TARGET_PCT), stop_loss + 0.01)
    return stop_loss, target_price


def _system_user_id():
    row = ensure_user_profile(SYSTEM_USERNAME)
    return row["id"]


def _resolve_user_id(username: Optional[str] = None) -> int:
    if username:
        row = ensure_user_profile(username)
        return row["id"]
    return _system_user_id()


def fetch_position(symbol: str, username: Optional[str] = None):
    conn = _get_conn(); c = conn.cursor()
    c.execute("SELECT * FROM positions WHERE user_id = :1 AND symbol = :2 AND status = 'OPEN'", [_resolve_user_id(username), symbol.upper()])
    rows = _rows(c); conn.close()
    return rows[0] if rows else None


def record_position(symbol: str, qty: float, price: float, timestamp=None, guardrail_reason=None, rl_confidence=None, username: Optional[str] = None):
    if qty <= 0 or price <= 0:
        return
    user_id = _resolve_user_id(username)
    stop_loss, target_price = _default_stop_target(price)
    existing = fetch_position(symbol, username=username)
    if existing:
        total_qty = existing["quantity"] + qty
        if total_qty <= 0:
            delete_position(user_id, symbol)
            return
        avg_price = (existing["quantity"] * existing["entry_price"] + qty * price) / total_qty
        upsert_position(user_id, symbol, int(total_qty), avg_price, min(stop_loss, existing.get("stop_loss") or stop_loss), max(target_price, existing.get("target_price") or target_price), guardrail_reason or existing.get("guardrail_reason"), rl_confidence or existing.get("rl_confidence"))
    else:
        upsert_position(user_id, symbol, int(qty), price, stop_loss, target_price, guardrail_reason, rl_confidence)


def update_position(symbol: str, qty_delta: float, price: float, timestamp=None, username: Optional[str] = None):
    user_id = _resolve_user_id(username)
    existing = fetch_position(symbol, username=username)
    if not existing:
        return
    new_qty = existing["quantity"] + qty_delta
    if new_qty <= 0:
        delete_position(user_id, symbol); return
    stop_loss, target_price = _default_stop_target(price)
    upsert_position(user_id, symbol, int(new_qty), existing["entry_price"], min(stop_loss, existing.get("stop_loss") or stop_loss), max(target_price, existing.get("target_price") or target_price), existing.get("guardrail_reason"), existing.get("rl_confidence"))


def _seed_news_cache_from_file():
    if not NEWS_CACHE_FILE or not os.path.exists(NEWS_CACHE_FILE):
        return
    try:
        with open(NEWS_CACHE_FILE, "r") as fh:
            payload = json.load(fh)
    except Exception as exc:
        log.debug(f"Failed to read legacy news cache: {exc}")
        return
    for symbol, entry in payload.items():
        headlines = entry.get("headlines") or []
        if headlines:
            upsert_news_cache(symbol, [{"title": item} for item in headlines])
